import { Product, Pedido } from '@/types';

export const PRODUCTOS: Product[] = [
  {
    id: 'p1',
    nombre: 'Torta Red Velvet artesanal',
    proveedor: 'La Dulce Carola',
    proveedorId: 'v1',
    precio: 8500,
    unidad: 'unidad',
    rating: 4.9,
    distancia: 1.2,
    categoria: 'Pastelería',
    tags: ['postre', 'dulce', 'sin conservantes'],
    emoji: '🎂',
    color: 'from-pink-400 to-rose-500',
    descripcion: 'Torta húmeda con frosting de queso crema. Porciones para 12.',
    stock: 8,
    match: 96,
  },
  {
    id: 'p2',
    nombre: 'Pan de masa madre',
    proveedor: 'Hornero del Barrio',
    proveedorId: 'v2',
    precio: 1800,
    unidad: 'kg',
    rating: 4.8,
    distancia: 0.6,
    categoria: 'Panadería',
    tags: ['pan', 'fermentado', 'artesanal'],
    emoji: '🥖',
    color: 'from-amber-400 to-orange-500',
    descripcion: 'Pan rústico con 36hs de fermentación. Ideal para sandwich de autor.',
    stock: 24,
    match: 92,
  },
  {
    id: 'p3',
    nombre: 'Viandas sin TACC',
    proveedor: 'Cocina Libre',
    proveedorId: 'v3',
    precio: 3200,
    unidad: 'porción',
    rating: 4.7,
    distancia: 2.4,
    categoria: 'Viandas',
    tags: ['sin tacc', 'celíaco', 'saludable'],
    emoji: '🥗',
    color: 'from-leaf-400 to-leaf-600',
    descripcion: 'Menú rotativo apto celíacos certificado. Mínimo 10 porciones.',
    stock: 50,
    match: 89,
  },
  {
    id: 'p4',
    nombre: 'Brownie vegano premium',
    proveedor: 'Plant Bakery',
    proveedorId: 'v4',
    precio: 950,
    unidad: 'unidad',
    rating: 4.9,
    distancia: 3.1,
    categoria: 'Pastelería',
    tags: ['vegano', 'postre', 'cacao puro'],
    emoji: '🍫',
    color: 'from-amber-700 to-stone-800',
    descripcion: 'Brownie 100% plant-based con nueces. Sin huevo ni lácteos.',
    stock: 60,
    match: 87,
  },
  {
    id: 'p5',
    nombre: 'Empanadas gourmet x12',
    proveedor: 'La Bodeguita',
    proveedorId: 'v5',
    precio: 6800,
    unidad: 'docena',
    rating: 4.6,
    distancia: 1.8,
    categoria: 'Salado',
    tags: ['salado', 'congelado', 'horno'],
    emoji: '🥟',
    color: 'from-yellow-400 to-amber-500',
    descripcion: 'Variedades clásicas + carne picante. Cocción en horno 12 min.',
    stock: 30,
    match: 84,
  },
  {
    id: 'p6',
    nombre: 'Jugos prensados en frío',
    proveedor: 'Verde Que Te Quiero',
    proveedorId: 'v6',
    precio: 1400,
    unidad: 'botella 330ml',
    rating: 4.8,
    distancia: 2.0,
    categoria: 'Bebidas',
    tags: ['saludable', 'fresco', 'detox'],
    emoji: '🥤',
    color: 'from-leaf-300 to-leaf-500',
    descripcion: 'Frutas y verduras orgánicas. Vence en 5 días refrigerado.',
    stock: 40,
    match: 81,
  },
  {
    id: 'p7',
    nombre: 'Café especialidad x kg',
    proveedor: 'Tostadores del Sur',
    proveedorId: 'v7',
    precio: 12500,
    unidad: 'kg',
    rating: 4.9,
    distancia: 4.5,
    categoria: 'Bebidas',
    tags: ['café', 'specialty', 'tostado'],
    emoji: '☕',
    color: 'from-stone-700 to-stone-900',
    descripcion: 'Blend de Brasil + Colombia. Tueste medio, perfecto espresso.',
    stock: 18,
    match: 78,
  },
  {
    id: 'p8',
    nombre: 'Alfajores de maicena x24',
    proveedor: 'La Dulce Carola',
    proveedorId: 'v1',
    precio: 5400,
    unidad: 'caja',
    rating: 4.9,
    distancia: 1.2,
    categoria: 'Pastelería',
    tags: ['postre', 'tradicional'],
    emoji: '🍪',
    color: 'from-amber-200 to-amber-400',
    descripcion: 'Tapas hechas a mano + dulce de leche colonial.',
    stock: 22,
    match: 75,
  },
  {
    id: 'p9',
    nombre: 'Hamburguesas vegetales x10',
    proveedor: 'Plant Bakery',
    proveedorId: 'v4',
    precio: 7200,
    unidad: 'pack',
    rating: 4.7,
    distancia: 3.1,
    categoria: 'Salado',
    tags: ['vegano', 'congelado'],
    emoji: '🍔',
    color: 'from-leaf-500 to-emerald-700',
    descripcion: 'Base de lentejas y remolacha. Plancha 6 min.',
    stock: 35,
    match: 72,
  },
  {
    id: 'p10',
    nombre: 'Yogur natural artesanal x6',
    proveedor: 'Tambo Cerca',
    proveedorId: 'v8',
    precio: 4200,
    unidad: 'pack',
    rating: 4.8,
    distancia: 5.2,
    categoria: 'Lácteos',
    tags: ['lácteo', 'fresco', 'probiótico'],
    emoji: '🥛',
    color: 'from-blue-200 to-blue-400',
    descripcion: 'Yogur entero sin aditivos. Refrigerado.',
    stock: 28,
    match: 70,
  },
  {
    id: 'p11',
    nombre: 'Cookies con chips x20',
    proveedor: 'Hornero del Barrio',
    proveedorId: 'v2',
    precio: 3600,
    unidad: 'caja',
    rating: 4.7,
    distancia: 0.6,
    categoria: 'Pastelería',
    tags: ['postre', 'horneado'],
    emoji: '🍪',
    color: 'from-amber-400 to-amber-600',
    descripcion: 'Cookies estilo americano con chips de chocolate semi amargo.',
    stock: 45,
    match: 68,
  },
  {
    id: 'p12',
    nombre: 'Pasta fresca rellena',
    proveedor: 'Nonna Lucia',
    proveedorId: 'v9',
    precio: 3800,
    unidad: 'kg',
    rating: 4.9,
    distancia: 2.8,
    categoria: 'Salado',
    tags: ['fresco', 'salado', 'italiano'],
    emoji: '🍝',
    color: 'from-yellow-300 to-orange-400',
    descripcion: 'Sorrentinos jamón y queso o ricota y nuez. Hervir 4 min.',
    stock: 15,
    match: 65,
  },
];

export const CATEGORIAS = ['Todos', 'Pastelería', 'Panadería', 'Viandas', 'Salado', 'Bebidas', 'Lácteos'];

export const PEDIDOS_COMPRADOR: Pedido[] = [
  { id: 'o1', producto: 'Pan de masa madre', cantidad: 5, total: 9000, estado: 'en camino', fecha: 'Hoy 14:30', proveedor: 'Hornero del Barrio', emoji: '🥖' },
  { id: 'o2', producto: 'Torta Red Velvet', cantidad: 2, total: 17000, estado: 'aceptado', fecha: 'Mañana 10:00', proveedor: 'La Dulce Carola', emoji: '🎂' },
  { id: 'o3', producto: 'Café especialidad', cantidad: 3, total: 37500, estado: 'entregado', fecha: 'Ayer', proveedor: 'Tostadores del Sur', emoji: '☕' },
];

export const PEDIDOS_VENDEDOR: Pedido[] = [
  { id: 'v-o1', producto: 'Brownie vegano premium', cantidad: 24, total: 22800, estado: 'pendiente', fecha: 'Hace 5 min', comprador: 'Café Norte', emoji: '🍫' },
  { id: 'v-o2', producto: 'Hamburguesas vegetales', cantidad: 3, total: 21600, estado: 'aceptado', fecha: 'Hoy 09:12', comprador: 'Bistró Roma', emoji: '🍔' },
  { id: 'v-o3', producto: 'Brownie vegano premium', cantidad: 12, total: 11400, estado: 'en camino', fecha: 'Ayer', comprador: 'Resto Las Cañitas', emoji: '🍫' },
  { id: 'v-o4', producto: 'Brownie vegano premium', cantidad: 30, total: 28500, estado: 'entregado', fecha: 'Hace 2 días', comprador: 'Cadena Verde', emoji: '🍫' },
];

export const RECOMENDACIONES_IA = [
  { tag: 'Sin TACC', motivo: 'Detectamos demanda en tu zona +40%', emoji: '🌾' },
  { tag: 'Postres veganos', motivo: '3 clientes habituales lo pidieron', emoji: '🌱' },
  { tag: 'Brunch del finde', motivo: 'Tu menú no lo cubre y es trending', emoji: '🥐' },
];

export const PROVI_BOT_FLOW = [
  { key: 'producto', q: '¡Hola! Soy Provi 🤖 ¿Qué estás necesitando hoy?', placeholder: 'Ej: necesito tortas para un evento' },
  { key: 'cantidad', q: 'Genial 🎯 ¿Qué cantidad necesitás?', placeholder: 'Ej: 20 unidades' },
  { key: 'fecha', q: '¿Para cuándo lo necesitás?', options: ['Hoy', 'Mañana', 'Esta semana', 'Próxima semana'] },
  { key: 'presupuesto', q: '¿Cuál es tu presupuesto aproximado?', options: ['Hasta $5.000', '$5.000 - $15.000', '$15.000 - $50.000', '+$50.000'] },
  { key: 'extra', q: '¿Algún requisito especial? (opcional)', options: ['Sin TACC', 'Vegano', 'Orgánico', 'Sin requisitos'] },
];

export function findMatches(query: string): typeof PRODUCTOS {
  const q = query.toLowerCase();
  const scored = PRODUCTOS.map(p => ({
    ...p,
    match: Math.floor(60 + Math.random() * 35 + (p.nombre.toLowerCase().includes(q.split(' ').pop() || '') ? 5 : 0)),
  }));
  return scored.sort((a, b) => (b.match || 0) - (a.match || 0)).slice(0, 4);
}
